//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs_Trainer
    {
        public int IdTrainer { get; set; }
        public int UserId { get; set; }
        public string Достижения { get; set; }
        public string Опыт_работы { get; set; }
    
        public virtual Kurs_User Kurs_User { get; set; }
    }
}
